services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tinchopipa/teamtodoapp-frontend:latest
    ports:
      - "80:80"  
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tinchopipa/teamtodoapp-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}  # URL de la base de datos PostgreSQL en settings.py
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}  # Google OAuth para el backend en la view de validacion
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}  # Google OAuth para el backend
      - ENVIRONMENT=${ENVIRONMENT}  # Ambiente de ejecución para el backend
      - SECRET_KEY=${SECRET_KEY}  # Clave secreta para el backend
      - DEBUG=${DEBUG}  # Modo debug para el backend
    restart: always