services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tinchopipa/teamtodoapp-frontend:latest
    ports:
      - "80:80"  
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tinchopipa/teamtodoapp-backend:latest
    ports:
      - "8000:8000"
    restart: always