services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args: # Pasar variables al momento del build
        VITE_BACKEND_URL: ${BACKEND_URL}
        VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    env_file:
    - .env 
    image: tinchopipa/teamtodoapp-frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tinchopipa/teamtodoapp-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}  # URL de la base de datos en Railway
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ENVIRONMENT=${ENVIRONMENT}  # Diferenciar entre 'development' y 'production'
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}  # Cambiar a false en producción
    env_file:
    - .env 
    restart: always
    networks:
      - app_network

networks:
  app_network: